services:
  documentation_server:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - ${PORT}:8080
    volumes:
      - ${DOCUMENTATION_DIR}:/usr/src/app/docs
      - ${ASSETS_DIR}:/usr/src/app/public/assets
